FROM tensorflow/tensorflow:2.1.0-py3

RUN pip install -U pip
RUN pip install numpy==1.16.0
RUN pip install pandas==1.1.5
RUN pip install scikit-learn==0.22.2
RUN pip install matplotlib==3.3.4
RUN pip install pyarrow==6.0.1